/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-03-05 19:52:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class weatherForecast_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    <meta contentType=\"text/html; charset=\"UTF-8\"/>\r\n");
      out.write("       <link rel=\"stylesheet\" href=\"../bootstrap/css/bootstrap.min.css\"/>      \r\n");
      out.write("       <script src=\"..//bootstrap/js/bootstrap.min.js\"></script>   \r\n");
      out.write("       <style>\r\n");
      out.write("\t\t        .jumbotron { \r\n");
      out.write("   \t\t\t      /* background-color: \t#00BFFF; Orange */\r\n");
      out.write("              background-image:url(\"sky-22.jpg\");\r\n");
      out.write("    \t\t      color: #ffffff;\r\n");
      out.write("    \t\t      padding: 100px 25px;\r\n");
      out.write("              font-family: Montserrat, sans-serif;\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("            .container-fluid {\r\n");
      out.write("              padding: 100px 50px;\r\n");
      out.write("            }\r\n");
      out.write("\t\t        .bg-grey {\r\n");
      out.write("    \t\t      background-color: #f6f6f6;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\r\n");
      out.write("\t\t        .container-fluid {\r\n");
      out.write("    \t\t      padding: 60px 50px;\r\n");
      out.write("\t\t        }\r\n");
      out.write("            .logo-small {\r\n");
      out.write("              /*color: #f4511e;*/\r\n");
      out.write("              font-size: 50px;\r\n");
      out.write("            }\r\n");
      out.write("            .logo {\r\n");
      out.write("              font-size: 200px;\r\n");
      out.write("            }\r\n");
      out.write("            .weather-info{\r\n");
      out.write("              font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .city-info{\r\n");
      out.write("              font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            body {\r\n");
      out.write("              font: 400 15px Lato, sans-serif;\r\n");
      out.write("              line-height: 1.8;\r\n");
      out.write("             \r\n");
      out.write("            }\r\n");
      out.write("          \r\n");
      out.write("            @media screen and (max-width: 768px) {\r\n");
      out.write("            .col-sm-4 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 25px 0;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\t\t    </style>    \r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>          \r\n");
      out.write("       \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"jumbotron text-center bg-grey\">\r\n");
      out.write("  \t\t\t<h1>Weather Forecast</h1> \r\n");
      out.write("  \t\t\t<p>Check the forecast for your city</p> \r\n");
      out.write("  \t\t\t <form class=\"form-inline\" action=\"/weather\" method=\"get\" id=\"seachEmployeeForm\" role=\"form\">\r\n");
      out.write("         <input type=\"hidden\" id=\"searchAction\" name=\"searchAction\" value=\"searchByCity\">\r\n");
      out.write("    \t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t<input type=\"text\" name=\"cityName\" id=\"cityName\" class=\"form-control\" size=\"50\" placeholder=\"City\"   required>\r\n");
      out.write("      \t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("        \t\t    <button type=\"submit\" class=\"btn btn-danger\">Check</button>\r\n");
      out.write("      \t\t\t  </div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("  \t\t\t </form>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("     ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("     ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /jsp/weatherForecast.jsp(82,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty weatherData[0].name }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" \r\n");
        out.write("    <div class=\"container-fluid\">\r\n");
        out.write("        <div class=\"row\">\r\n");
        out.write("          <div class=\"col-sm-5 col-xs-6 col-md-3 city-info\">\r\n");
        out.write("            <!-- <span class=\"glyphicon glyphicon-signal logo\"></span> -->\r\n");
        out.write("            \r\n");
        out.write("            <div class=\"media\">\r\n");
        out.write("              <div class=\"media-left \">\r\n");
        out.write("                <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].weather[0].icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"  alt=\"Cinque Terre\" width=\"120\" height=\"120\">\r\n");
        out.write("              </div>\r\n");
        out.write("              <div class=\"media-body\">\r\n");
        out.write("                <h1>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].main.celsiusTemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("<small>°C</small></h1>\r\n");
        out.write("                <h1>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h1>\r\n");
        out.write("                <h3>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h3> \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].weather[0].description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("              </div>\r\n");
        out.write("           </div>\r\n");
        out.write("          </div>\r\n");
        out.write("         \r\n");
        out.write("          <div class=\"col-sm-2 col-xs-3 col-md-2 weather-info\">\r\n");
        out.write("          <!--   <div class=\"panel panel-default\">\r\n");
        out.write("              <div class=\"panel-header\"></div>\r\n");
        out.write("              <div class=\"panel-body\"> \r\n");
        out.write("                <p><strong>Humidity</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].main.humidity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("                <p><strong>Wind</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].wind.speed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" m/s</p>\r\n");
        out.write("                <p><strong>Clouds</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].clouds.all}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("%</p>\r\n");
        out.write("              \r\n");
        out.write("              </div>\r\n");
        out.write("            </div>  -->\r\n");
        out.write("        <table class=\"table table-striped table-bordered table-condensed\">\r\n");
        out.write("    <thead>\r\n");
        out.write("     <!--  <tr>\r\n");
        out.write("        <th>Firstname</th>\r\n");
        out.write("        <th>Lastname</th>\r\n");
        out.write("      </tr> -->\r\n");
        out.write("    </thead>\r\n");
        out.write("    <tbody>\r\n");
        out.write("      <tr>\r\n");
        out.write("        <td>Humidity</td>\r\n");
        out.write("        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].main.humidity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" </td>\r\n");
        out.write("       \r\n");
        out.write("      </tr>\r\n");
        out.write("      <tr>\r\n");
        out.write("        <td>Wind</td>\r\n");
        out.write("        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].wind.speed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" m/s</td>\r\n");
        out.write("      \r\n");
        out.write("      </tr>\r\n");
        out.write("       <tr>\r\n");
        out.write("        <td>Clouds</td>\r\n");
        out.write("        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].clouds.all}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("% </td>\r\n");
        out.write("       \r\n");
        out.write("      </tr>\r\n");
        out.write("\r\n");
        out.write("       <tr>\r\n");
        out.write("        <td>Preassure</td>\r\n");
        out.write("        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].main.pressure}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" hPa</td>\r\n");
        out.write("      \r\n");
        out.write("      </tr>\r\n");
        out.write("      <tr>\r\n");
        out.write("        <td>Sunrise</td>\r\n");
        out.write("        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].sys.sunRise}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" </td>\r\n");
        out.write("      \r\n");
        out.write("      </tr>\r\n");
        out.write("      <tr>\r\n");
        out.write("        <td>Sunset</td>\r\n");
        out.write("        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].sys.sunSet}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" </td>\r\n");
        out.write("      \r\n");
        out.write("      </tr>\r\n");
        out.write("   \r\n");
        out.write("     \r\n");
        out.write("    </tbody>\r\n");
        out.write("  </table>\r\n");
        out.write("          \r\n");
        out.write("\r\n");
        out.write("          </div>\r\n");
        out.write("\r\n");
        out.write("          <div class=\"col-sm-5 col-xs-3 col-md-7\"></div>\r\n");
        out.write("           \r\n");
        out.write("          \r\n");
        out.write("        </div>\r\n");
        out.write("    </div>\r\n");
        out.write("     \r\n");
        out.write("\r\n");
        out.write("    \r\n");
        out.write("\r\n");
        out.write("  <!--   <div class=\"container-fluid bg-grey\">\r\n");
        out.write("        <h2>Our Values</h2>\r\n");
        out.write("        <h4><strong>MISSION:</strong> Our mission lorem ipsum..</h4> \r\n");
        out.write("        <p><strong>VISION:</strong> Our vision Lorem ipsum..\r\n");
        out.write("    </div>\r\n");
        out.write(" -->\r\n");
        out.write("   \r\n");
        out.write("\r\n");
        out.write("    <div class=\"container-fluid\">\r\n");
        out.write("  <div class=\"text-center\">\r\n");
        out.write("    <h2>Forecast</h2>\r\n");
        out.write("    <h4>Weather for following days</h4>\r\n");
        out.write("  </div>\r\n");
        out.write("  <div class=\"row\">\r\n");
        out.write("    <div class=\"col-sm-3\">\r\n");
        out.write("      <div class=\"panel panel-default text-center\">\r\n");
        out.write("        <div class=\"panel-heading\">\r\n");
        out.write("          <h1>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[1].dayOfWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h1>\r\n");
        out.write("          ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[1].dateWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("        <div class=\"panel-body\">\r\n");
        out.write("         \r\n");
        out.write("                <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[1].weather[0].icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"  alt=\"Cinque Terre\" width=\"120\" height=\"120\">\r\n");
        out.write("            \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[1].main.celsiusTemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" °C</p>\r\n");
        out.write("            \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[1].weather[0].description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("               \r\n");
        out.write("        </div>\r\n");
        out.write("       \r\n");
        out.write("      </div> \r\n");
        out.write("    </div> \r\n");
        out.write("    <div class=\"col-sm-3\">\r\n");
        out.write("      <div class=\"panel panel-default text-center\">\r\n");
        out.write("        <div class=\"panel-heading\">\r\n");
        out.write("          <h1>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[2].dayOfWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h1>\r\n");
        out.write("          ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[2].dateWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("        <div class=\"panel-body\">\r\n");
        out.write("         \r\n");
        out.write("                <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[2].weather[0].icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"  alt=\"Cinque Terre\" width=\"120\" height=\"120\">\r\n");
        out.write("            \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[2].main.celsiusTemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" °C</p>\r\n");
        out.write("            \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[2].weather[0].description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("        </div>\r\n");
        out.write("      \r\n");
        out.write("      </div> \r\n");
        out.write("    </div> \r\n");
        out.write("   <div class=\"col-sm-3\">\r\n");
        out.write("      <div class=\"panel panel-default text-center\">\r\n");
        out.write("        <div class=\"panel-heading\">\r\n");
        out.write("          <h1>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[3].dayOfWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h1>\r\n");
        out.write("          ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[3].dateWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("        <div class=\"panel-body\">\r\n");
        out.write("           \r\n");
        out.write("          \r\n");
        out.write("                <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[3].weather[0].icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"  alt=\"Cinque Terre\" width=\"120\" height=\"120\">\r\n");
        out.write("            \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[3].main.celsiusTemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" °C</p>\r\n");
        out.write("             \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[3].weather[0].description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("               \r\n");
        out.write("             \r\n");
        out.write("          \r\n");
        out.write("        </div>\r\n");
        out.write("       <!--  <div class=\"panel-footer\">\r\n");
        out.write("          <h3>$49</h3>\r\n");
        out.write("          <h4>per month</h4>\r\n");
        out.write("          <button class=\"btn btn-lg\">Sign Up</button>\r\n");
        out.write("        </div> -->\r\n");
        out.write("      </div> \r\n");
        out.write("    </div> \r\n");
        out.write("\r\n");
        out.write("    <div class=\"col-sm-3\">\r\n");
        out.write("      <div class=\"panel panel-default text-center\">\r\n");
        out.write("        <div class=\"panel-heading\">\r\n");
        out.write("          <h1>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[4].dayOfWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h1>\r\n");
        out.write("          ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[4].dateWeek}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("        </div>\r\n");
        out.write("        <div class=\"panel-body\">\r\n");
        out.write("           \r\n");
        out.write("          \r\n");
        out.write("                <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[4].weather[0].icon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\"  alt=\"Cinque Terre\" width=\"120\" height=\"120\">\r\n");
        out.write("            \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[4].main.celsiusTemp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" °C</p>\r\n");
        out.write("             \r\n");
        out.write("                <p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[4].weather[0].description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("               \r\n");
        out.write("             \r\n");
        out.write("          \r\n");
        out.write("        </div>\r\n");
        out.write("       <!--  <div class=\"panel-footer\">\r\n");
        out.write("          <h3>$49</h3>\r\n");
        out.write("          <h4>per month</h4>\r\n");
        out.write("          <button class=\"btn btn-lg\">Sign Up</button>\r\n");
        out.write("        </div> -->\r\n");
        out.write("      </div> \r\n");
        out.write("    </div> \r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("  </div>\r\n");
        out.write("</div>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("    <div id=\"googleMap\" style=\"height:400px;width:100%;\"></div>\r\n");
        out.write("\r\n");
        out.write("<!-- Add Google Maps -->\r\n");
        out.write("<script src=\"http://maps.googleapis.com/maps/api/js\"></script>\r\n");
        out.write("<script>\r\n");
        out.write("var myCenter = new google.maps.LatLng(");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].coord.lat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(',');
        out.write(' ');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${weatherData[0].coord.lon}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(");\r\n");
        out.write("\r\n");
        out.write("function initialize() {\r\n");
        out.write("var mapProp = {\r\n");
        out.write("center:myCenter,\r\n");
        out.write("zoom:12,\r\n");
        out.write("scrollwheel:false,\r\n");
        out.write("draggable:false,\r\n");
        out.write("mapTypeId:google.maps.MapTypeId.ROADMAP\r\n");
        out.write("};\r\n");
        out.write("\r\n");
        out.write("var map = new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
        out.write("\r\n");
        out.write("var marker = new google.maps.Marker({\r\n");
        out.write("position:myCenter,\r\n");
        out.write("});\r\n");
        out.write("\r\n");
        out.write("marker.setMap(map);\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("google.maps.event.addDomListener(window, 'load', initialize);\r\n");
        out.write("</script>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("     <div class=\"container-fluid text-center\">\r\n");
        out.write("  <h2>Forcast</h2>\r\n");
        out.write("  <h4>What we offer</h4>\r\n");
        out.write("  <br>\r\n");
        out.write("  <div class=\"row\">\r\n");
        out.write("    <div class=\"col-sm-4\">\r\n");
        out.write("      <span class=\"glyphicon glyphicon-cloud logo-small\"></span>\r\n");
        out.write("      <h4>Current Weather</h4>\r\n");
        out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
        out.write("    </div>\r\n");
        out.write("    <div class=\"col-sm-4\">\r\n");
        out.write("      <span class=\"glyphicon glyphicon-certificate logo-small\"></span>\r\n");
        out.write("      <h4>5 days forecast</h4>\r\n");
        out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
        out.write("    </div>\r\n");
        out.write("    <div class=\"col-sm-4\">\r\n");
        out.write("      <span class=\"glyphicon glyphicon-grain logo-small\"></span>\r\n");
        out.write("      <h4>someotherstufE</h4>\r\n");
        out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
        out.write("    </div>\r\n");
        out.write("    </div>\r\n");
        out.write("    <br><br>\r\n");
        out.write("    </div>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
